src/Entity/User.php
<?php

namespace App\Entity;

use App\Enum\DocumentIdentityTypeEnum;
use App\Enum\GroupType;
use App\Enum\UserStatus;
use App\Repository\UserRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Event\LifecycleEventArgs;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\PersistentCollection;
use Exception;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use JetBrains\PhpStorm\Internal\LanguageLevelTypeAware;
use Mgilet\NotificationBundle\Annotation\Notifiable;
use Mgilet\NotificationBundle\NotifiableInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Security\Core\User\EquatableInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Vich\UploaderBundle\Entity\File as EmbeddedFile;
use Symfony\Component\Serializer\Annotation\Groups;


/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 * @ORM\HasLifecycleCallbacks
 * @ORM\EntityListeners({"App\Entity\Listener\UserListener"})
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 * @Vich\Uploadable
 * @Notifiable(name="user")
 */
class User implements UserInterface, EquatableInterface, \Serializable, NotifiableInterface
{
  use TimestampableEntity;

  public function __construct()
  {
    $this->individualPermissions = new ArrayCollection();
    $this->posts = new ArrayCollection();
    $this->groups = new ArrayCollection();
    $this->userStatus = UserStatus::get(UserStatus::PENDING);
    $this->commentaires = new ArrayCollection();
    $this->likes = new ArrayCollection();

    $this->events = new ArrayCollection();
    $this->calls = new ArrayCollection();
    $this->identityType = DocumentIdentityTypeEnum::UNKNOWN();
    $this->avatar = new EmbeddedFile();
    $this->serviceRequests = new ArrayCollection();
    $this->UserCall = new ArrayCollection();
    $this->postCategories = new ArrayCollection();
    $this->groupPosts = new ArrayCollection();
    $this->groupes = new ArrayCollection();
    $this->contacts = new ArrayCollection();
    $this->contacted_by = new ArrayCollection();
    $this->messages = new ArrayCollection();
    $this->channels = new ArrayCollection();

  }

  //<editor-fold desc="id">

  /**
   * @ORM\Id
   * @ORM\GeneratedValue
   * @ORM\Column(type="integer")
   * @Groups("post:read")
   */
  private $id;

  public function getId(): ?int
  {
    return $this->id;
  }
  //</editor-fold>
  //<editor-fold desc="Avatar">
  /**
   * NOTE: This is not a mapped field of entity metadata, just a simple property.
   *
   * @Vich\UploadableField(
   *   mapping="avatar_image",
   *   fileNameProperty="avatar.name"
   * )
   *
   * @var File|null
   */
  private ?File $avatarFile = null;

  public function setAvatarFile(File|UploadedFile|null $avatarFile = null): static
  {
    $this->avatarFile = $avatarFile;
    if ($avatarFile !== null) {
      $this->updatedAt = new \DateTimeImmutable();
    }
    return $this;
  }

  public function getAvatarFile(): ?File
  {
    return $this->avatarFile;
  }

  /**
   * @ORM\Embedded(class="Vich\UploaderBundle\Entity\File")
   * @Groups ("Service")
   * @Groups ("Request")
   */
  private ?EmbeddedFile $avatar;

  public function setAvatar(?EmbeddedFile $avatar): static
  {
    $this->avatar = $avatar;
    return $this;
  }

  public function getAvatar(): ?EmbeddedFile
  {
    return $this->avatar;
  }
  //</editor-fold>
  //<editor-fold desc="First Name">
  /**
   * @Assert\NotNull
   * @Assert\Length(min=3, max=16)
   * @Assert\Regex(
   *     pattern="/\d/",
   *     match=false,
   *     message="Your name cannot contain a number"
   * )
   * @ORM\Column(type="string", length=20)
   * @Groups("post:read")
   * @Groups ("Service")
   * @Groups ("Request")
   */
  private ?string $first_name = null;

  public function getFirstName(): ?string
  {
    return $this->first_name;
  }

  public function setFirstName(?string $first_name): self
  {
    $this->first_name = $first_name;
    return $this;
  }
  //</editor-fold>
  //<editor-fold desc="Last Name">
  /**
   * @Assert\NotNull
   * @Assert\Length(min=3, max=16)
   * @Assert\Regex(
   *     pattern="/\d/",
   *     match=false,
   *     message="Your name cannot contain a number"
   * )
   * @ORM\Column(type="string", length=25)
   * @Groups("post:read")
   * @Groups ("Service")
   * @Groups ("Request")
   */
  private ?string $last_name = null;

  public function getLastName(): ?string
  {
    return $this->last_name;
  }

  public function setLastName(?string $last_name): self
  {
    $this->last_name = $last_name;
    return $this;
  }
  //</editor-fold>
  //<editor-fold desc="Email">
  /**
   * @Assert\NotBlank
   * @Assert\Email(
   *    message = "The email '{{ value }}' is not a valid email."
   * )
   * @var string|null
   * @ORM\Column(type="string", unique=true)
   * @Groups("post:read")
   */
  protected ?string $email = null;

  public function getEmail(): ?string
  {
    return $this->email;
  }

  public function setEmail(?string $email): static
  {
    $this->email = $email;
    return $this;
  }
  //</editor-fold>
  //<editor-fold desc="Phone Number">
  /**
   * @Assert\Regex("/^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$/",
   * message="Respect this format: +21611111111")
   * @ORM\Column(type="string", length=255, nullable=true)
   * @Assert\NotBlank
   * @Groups("post:read")
   */
  private ?string $phoneNumber = null;

  public function getPhoneNumber(): ?string
  {
    return $this->phoneNumber;
  }

  public function setPhoneNumber(?string $phonenumber): self
  {
    $this->phoneNumber = $phonenumber;
    return $this;
  }
  //</editor-fold>
  //<editor-fold desc="Class">
  /**
   * @Assert\Regex("/^([1-5](A|B|TWIN|SLEAMS)\d{1,3})|$/")
   * @ORM\Column(type="string", length=255, nullable=true)
   */
  private $class;

  public function getClass(): ?string
  {
    return $this->class;
  }

  public function setClass(?string $class): self
  {
    $this->class = $class;

    return $this;
  }
  //</editor-fold>
  //<editor-fold desc="PlainPassword">
  /**
   * @var string|null
   * @Assert\Expression(
   *   "(this.getPassword() != '' and value == '') or (value != '' and this.getPassword() == '')",
   *    message="A password of at least 6 characters must be set."
   * )
   * @Groups("post:read")
   */
  protected ?string $plainPassword = null;

  public function setPlainPassword(?string $password): static
  {
    if (empty($password)) {
      return $this;
    }
    $this->plainPassword = $password;
    $this->password = null;
    return $this;
  }

  public function getPlainPassword(): ?string
  {
    return $this->plainPassword;
  }
  //</editor-fold>
  //<editor-fold desc="Password">
  /**
   * @var string The hashed password
   * @ORM\Column(type="string")
   * @Groups("post:read")
   */
  private $password;

  /**
   * @see UserInterface
   */
  public function getPassword(): ?string
  {
    return $this->password;
  }

  public function setPassword(string $password): self
  {
    $this->password = $password;
    return $this;
  }

  public function getSalt()
  {
    return null; // todo: for now.
  }

  //</editor-fold>
  //<editor-fold desc="LastLogin">
  /**
   * @ORM\Column(type="datetime", nullable=true)
   */
  protected ?DateTime $last_login;

  public function getLastLogin(): ?DateTime
  {
    return $this->last_login;
  }

  public function setLastLogin(DateTime $time = null)
  {
    $this->last_login = $time;
    return $this;
  }
  //</editor-fold>
  //<editor-fold desc="LastActive">
  /**
   * @ORM\Column(name="last_activity_at", type="datetime", nullable=true)
   */
  protected ?DateTime $lastActivityAt = null;

  public function setLastActivityAt(?DateTime $lastActivityAt): static
  {
    $this->lastActivityAt = $lastActivityAt;
    return $this;
  }

  public function getLastActivityAt(): ?DateTime
  {
    return $this->lastActivityAt;
  }

  public function isActiveNow(): bool
  {
    $delay = new DateTime('5 minutes ago');
    return ($this->getLastActivityAt() > $delay);
  }
  //</editor-fold>
  //<editor-fold desc="ConfirmationToken">
  /**
   * @Column(type="string", nullable=true)
   */
  protected ?string $confirmationToken = null;

  public function getConfirmationToken(): ?string
  {
    return $this->confirmationToken;
  }

  public function setConfirmationToken(string $confirmationToken): static
  {
    $this->confirmationToken = $confirmationToken;

    return $this;
  }
  //</editor-fold>
  //<editor-fold desc="PasswordRequestedAt">
  /**
   * @ORM\Column(type="datetime", nullable=true)
   */
  protected ?DateTime $passwordRequestedAt;

  public function setPasswordRequestedAt(DateTime $date = null): static
  {
    $this->passwordRequestedAt = $date;
    return $this;
  }

  public function getPasswordRequestedAt(): ?DateTime
  {
    return $this->passwordRequestedAt;
  }
  //</editor-fold>
  //<editor-fold desc="UserStatus">
  /**
   * @Assert\NotNull
   * @Elao\Enum\Bridge\Symfony\Validator\Constraint\Enum(class=UserStatus::class)
   * @ORM\Column(type="userstatus")
   */
  protected UserStatus $userStatus;

  public function getUserStatus(): UserStatus
  {
    return $this->userStatus;
  }

  public function setUserStatus(UserStatus $userStatus): self
  {
    $this->userStatus = $userStatus;
    return $this;
  }
  //</editor-fold>
  //<editor-fold desc="Groups">
  /**
   * @ORM\ManyToMany(targetEntity=Group::class, inversedBy="members")
   */
  private $groups;

  /**
   * @return Collection<int, Group>
   */
  public function getGroups(): Collection
  {

templates/views/content/authentication/auth-check-email-cover.html.twig
{% extends 'views/layouts/fullLayoutMaster.html.twig' %}

{% block title %} Check your email {% endblock %}

{% block page_style %}
  <link rel="stylesheet" href="{{ asset('css/base/pages/authentication.css') }}">
{% endblock %}


{% block content %}
<div class="auth-wrapper auth-cover">
  <div class="auth-inner row m-0">
    <!-- Brand logo-->
    <a class="brand-logo" href="#">
      <svg viewbox="0 0 139 95" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="28">
        <defs>
          <lineargradient id="linearGradient-1" x1="100%" y1="10.5120544%" x2="50%" y2="89.4879456%">
            <stop stop-color="#000000" offset="0%"></stop>
            <stop stop-color="#FFFFFF" offset="100%"></stop>
          </lineargradient>
          <lineargradient id="linearGradient-2" x1="64.0437835%" y1="46.3276743%" x2="37.373316%" y2="100%">
            <stop stop-color="#EEEEEE" stop-opacity="0" offset="0%"></stop>
            <stop stop-color="#FFFFFF" offset="100%"></stop>
          </lineargradient>
        </defs>
        <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
          <g id="Artboard" transform="translate(-400.000000, -178.000000)">
            <g id="Group" transform="translate(400.000000, 178.000000)">
              <path class="text-primary" id="Path" d="M-5.68434189e-14,2.84217094e-14 L39.1816085,2.84217094e-14 L69.3453773,32.2519224 L101.428699,2.84217094e-14 L138.784583,2.84217094e-14 L138.784199,29.8015838 C137.958931,37.3510206 135.784352,42.5567762 132.260463,45.4188507 C128.736573,48.2809251 112.33867,64.5239941 83.0667527,94.1480575 L56.2750821,94.1480575 L6.71554594,44.4188507 C2.46876683,39.9813776 0.345377275,35.1089553 0.345377275,29.8015838 C0.345377275,24.4942122 0.230251516,14.560351 -5.68434189e-14,2.84217094e-14 Z" style="fill: currentColor"></path>
              <path id="Path1" d="M69.3453773,32.2519224 L101.428699,1.42108547e-14 L138.784583,1.42108547e-14 L138.784199,29.8015838 C137.958931,37.3510206 135.784352,42.5567762 132.260463,45.4188507 C128.736573,48.2809251 112.33867,64.5239941 83.0667527,94.1480575 L56.2750821,94.1480575 L32.8435758,70.5039241 L69.3453773,32.2519224 Z" fill="path(#linearGradient-1)" opacity="0.2"></path>
              <polygon id="Path-2" fill="#000000" opacity="0.049999997" points="69.3922914 32.4202615 32.8435758 70.5039241 54.0490008 16.1851325"></polygon>
              <polygon id="Path-21" fill="#000000" opacity="0.099999994" points="69.3922914 32.4202615 32.8435758 70.5039241 58.3683556 20.7402338"></polygon>
              <polygon id="Path-3" fill="path(#linearGradient-2)" opacity="0.099999994" points="101.428699 0 83.0667527 94.1480575 130.378721 47.0740288"></polygon>
            </g>
          </g>
        </g>
      </svg>
      <h2 class="brand-text text-primary ms-1">Vuexy</h2>
    </a>
    <!-- /Brand logo-->

    <!-- Left Text-->
    <div class="d-none d-lg-flex col-lg-8 align-items-center p-5">
      <div class="w-100 d-lg-flex align-items-center justify-content-center px-5">
        {% if configData['theme'] == 'dark' %}
         <img src="{{asset('images/illustration/verify-email-illustration-dark.svg')}}" class="img-fluid" alt="two steps verification" />
        {% else %}
        <img src="{{asset('images/illustration/verify-email-illustration.svg')}}" class="img-fluid" alt="two steps verification" />
        {% endif %}
        </div>
    </div>
    <!-- /Left Text-->

    <!-- verify email cover-->
    <div class="d-flex col-lg-4 align-items-center auth-bg px-2 p-lg-5">
      <div class="col-12 col-sm-8 col-md-6 col-lg-12 px-xl-2 mx-auto">
        <h2 class="card-title fw-bolder mb-1">Check your email &#x2709;&#xFE0F;</h2>
        <p class="card-text mb-2">A password recovery link was sent to your address. Please follow the link inside to continue.</p>
        <a class="btn btn-primary w-100" href="{{url('login')}}">Try logging in.</a>
        <p class="text-center mt-2"><span>Didn&apos;t receive an email?</span>
            <a href="{{ url('app_forgot_password_request') }}"><span>&nbsp;Try again.</span></a>
        </p>
      </div>
    </div>
    <!-- verify email cover-->
  </div>
</div>
{% endblock %}

templates/views/content/authentication/auth-forgot-password-cover.html.twig
{% extends 'views/layouts/fullLayoutMaster.html.twig' %}

{% block title %} Forgot Password {% endblock %}

{% block page_style %}
  <link rel="stylesheet" href="{{ asset('css/base/plugins/forms/form-validation.css') }}">
  <link rel="stylesheet" href="{{ asset('css/base/pages/authentication.css') }}">
{% endblock %}


{% block content %}
  <div class="auth-wrapper auth-cover">
    <div class="auth-inner row m-0">
      <!-- Brand logo-->
      <a class="brand-logo" href="#">
        <svg viewBox="0 0 139 95" version="1.1" xmlns="http://www.w3.org/2000/svg"
             xmlns:xlink="http://www.w3.org/1999/xlink" height="28">
          <defs>
            <lineargradient id="linearGradient-1" x1="100%" y1="10.5120544%" x2="50%" y2="89.4879456%">
              <stop stop-color="#000000" offset="0%"></stop>
              <stop stop-color="#FFFFFF" offset="100%"></stop>
            </lineargradient>
            <lineargradient id="linearGradient-2" x1="64.0437835%" y1="46.3276743%" x2="37.373316%" y2="100%">
              <stop stop-color="#EEEEEE" stop-opacity="0" offset="0%"></stop>
              <stop stop-color="#FFFFFF" offset="100%"></stop>
            </lineargradient>
          </defs>
          <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
            <g id="Artboard" transform="translate(-400.000000, -178.000000)">
              <g id="Group" transform="translate(400.000000, 178.000000)">
                <path class="text-primary" id="Path"
                      d="M-5.68434189e-14,2.84217094e-14 L39.1816085,2.84217094e-14 L69.3453773,32.2519224 L101.428699,2.84217094e-14 L138.784583,2.84217094e-14 L138.784199,29.8015838 C137.958931,37.3510206 135.784352,42.5567762 132.260463,45.4188507 C128.736573,48.2809251 112.33867,64.5239941 83.0667527,94.1480575 L56.2750821,94.1480575 L6.71554594,44.4188507 C2.46876683,39.9813776 0.345377275,35.1089553 0.345377275,29.8015838 C0.345377275,24.4942122 0.230251516,14.560351 -5.68434189e-14,2.84217094e-14 Z"
                      style="fill: currentColor"></path>
                <path id="Path1"
                      d="M69.3453773,32.2519224 L101.428699,1.42108547e-14 L138.784583,1.42108547e-14 L138.784199,29.8015838 C137.958931,37.3510206 135.784352,42.5567762 132.260463,45.4188507 C128.736573,48.2809251 112.33867,64.5239941 83.0667527,94.1480575 L56.2750821,94.1480575 L32.8435758,70.5039241 L69.3453773,32.2519224 Z"
                      fill="path(#linearGradient-1)" opacity="0.2"></path>
                <polygon id="Path-2" fill="#000000" opacity="0.049999997"
                         points="69.3922914 32.4202615 32.8435758 70.5039241 54.0490008 16.1851325"></polygon>
                <polygon id="Path-21" fill="#000000" opacity="0.099999994"
                         points="69.3922914 32.4202615 32.8435758 70.5039241 58.3683556 20.7402338"></polygon>
                <polygon id="Path-3" fill="path(#linearGradient-2)" opacity="0.099999994"
                         points="101.428699 0 83.0667527 94.1480575 130.378721 47.0740288"></polygon>
              </g>
            </g>
          </g>
        </svg>
        <h2 class="brand-text text-primary ms-1">Vuexy</h2>
      </a>
      <!-- /Brand logo-->

      <!-- Left Text-->
      <div class="d-none d-lg-flex col-lg-8 align-items-center p-5">
        <div class="w-100 d-lg-flex align-items-center justify-content-center px-5">
          {% if  configData['theme'] == 'dark' %}

            <img class="img-fluid" src="{{ asset('images/pages/forgot-password-v2-dark.svg') }}"
                 alt="Forgot password V2"/>
          {% else %}
            <img class="img-fluid" src="{{ asset('images/pages/forgot-password-v2.svg') }}" alt="Forgot password V2"/>
          {% endif %}
        </div>
      </div>
      <!-- /Left Text-->

      <!-- Forgot password-->
      <div class="d-flex col-lg-4 align-items-center auth-bg px-2 p-lg-5">
        <div class="col-12 col-sm-8 col-md-6 col-lg-12 px-xl-2 mx-auto">

          <h2 class="card-title fw-bold mb-1">Forgot Password? 🔒</h2>
          <p class="card-text mb-2">Enter your email and we'll send you instructions to reset your password</p>

          {% for flashError in app.flashes('reset_password_error') %}
            <div class="alert alert-danger px-1 py-1" role="alert">{{ flashError }}</div>
          {% endfor %}
          {{ form_start(requestForm,
            {"attr": {"action": url('app_forgot_password_request'), "medhod" : "POST"} } ) }}
            <div class="mb-1">
              {{ form_row(requestForm.email) }}
            </div>
            <button class="btn btn-primary w-100" tabindex="2">Send reset link</button>
          {{ form_end(requestForm) }}
          <p class="text-center mt-2">
            <a href="{{ url("login") }}">
              <i data-feather="chevron-left"></i> Back to login
            </a>
          </p>
        </div>
      </div>
      <!-- /Forgot password-->
    </div>
  </div>
{% endblock %}


{% block vendor_script %}
  <script src="{{ asset('vendors/js/forms/validation/jquery.validate.min.js') }}"></script>
{% endblock %}


{% block page_script %}
  <script src="{{ asset('js/scripts/pages/auth-forgot-password.js') }}"></script>
{% endblock %}

templates/views/content/authentication/auth-register-cover.html.twig
{% extends 'views/layouts/fullLayoutMaster.html.twig' %}

{% block title %} Register {% endblock %}

{% block page_style %}
  {# Page Css files #}
  <link rel="stylesheet" href="{{ asset('css/base/plugins/forms/form-validation.css') }}">
  <link rel="stylesheet" href="{{ asset('css/base/pages/authentication.css') }}">
{% endblock %}


{% block content %}
  <div class="auth-wrapper auth-cover">
    <div class="auth-inner row m-0">
      <!-- Brand logo-->
      <div class="brand-logo" style="width: 25%;height: 105px;">
        <img class="img-fluid" style="width: 80px;" src="{{ asset('images/pages/Logo.png') }}" alt="Logo"/>
        <h6 class="brand-text text-primary ms-1">Communiquer autrement</h6>
      </div>
      <!-- /Brand logo-->

      <!-- Left Text-->
      <div class="d-none d-lg-flex col-lg-8 align-items-center p-5">
        <div class="w-100 d-lg-flex align-items-center justify-content-center px-5">
          {% if configData['theme'] == 'dark' %} #}
            <img class="img-fluid" src="{{ asset('images/pages/register-v2-dark.svg') }}" alt="Register V2"/>
          {% else %}
            <img class="img-fluid" src="{{ asset('images/pages/register-v2.svg') }}" alt="Register V2"/>
          {% endif %}
        </div>
      </div>
      <!-- /Left Text-->

      <!-- Register-->
      <div class="d-flex col-lg-4 align-items-center auth-bg px-2 p-lg-5">
        <div class="col-12 col-sm-8 col-md-6 col-lg-12 px-xl-2 mx-auto">
          <h2 class="card-title fw-bold mb-1">Adventure starts here 🚀</h2>
          <p class="card-text mb-2">Signup for ESPRITx</p>
          {{ form_start(form, {'method': 'POST'}) }}
          {% for flash_error in app.flashes('verify_email_error') %}
            <div class="alert alert-danger" role="alert">{{ flash_error }}</div>
          {% endfor %}
          <div class="mb-1">
            {{ form_row(form.firstName) }}
          </div>
          <div class="mb-1">
            {{ form_row(form.lastName) }}
          </div>
          <div class="mb-1">
            {{ form_row(form.email) }}
          </div>
          <div class="mb-1">
            {{ form_row(form.plainPassword,{
              label: 'Password'
            }) }}
          </div>
          <div class="mb-1">
            {{ form_row(form.agreeTerms) }}
          </div>
          <button class="btn btn-primary w-100" tabindex="5">Sign up</button>
          {{ form_end(form) }}
          <p class="text-center mt-2">
            <span>Already have an account?</span>
            <a href="{{ path('login') }}"><span>&nbsp;Sign in instead</span></a>
          </p>
          <div class="divider my-2">
            <div class="divider-text">or</div>
          </div>
          <div class="auth-footer-btn d-flex justify-content-center">
            <a class="btn btn-google" href="{{ url('connect_google_start') }}"><i data-feather="mail"></i></a>
          </div>
        </div>
      </div>
      <!-- /Register-->
    </div>
  </div>
{% endblock %}


{% block vendor_script %}
  <script src="{{ asset('vendors/js/forms/validation/jquery.validate.min.js') }}"></script>
{% endblock %}


{% block page_script %}
  <script src="{{ asset('js/scripts/pages/auth-register.js') }}"></script>
{% endblock %}